#!/bin/bash -e
#
# Copyright (c) 2011 Joyent Inc., All rights reserved.
#

if [[ ! -f /root/.ssh/authorized_keys ]]; then
  authorized_keys=$(/lib/smartdc/mdata-get root_authorized_keys 2>>/dev/console)
  authorized_keys=$(echo -n "${authorized_keys}"| sed 's/\(ssh-rsa\ \)/\n\1/g' | sed 's/\(ssh-dss\ \)/\n\1/g')

  if [[ -n ${authorized_keys} ]]; then
    mkdir -p /root/.ssh
    echo "${authorized_keys}" > /root/.ssh/authorized_keys
    chmod 700 /root/.ssh
    chmod 600 /root/.ssh/authorized_keys
  else
    echo "mdata-get root_authorized_keys returned nothing"
    exit 1
  fi
fi

exit 0
